### ISSUE TITLE
updatecli: keep track of golang version

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/shared-tools#1]
This repository has golang code used for testing terraform.

It implies that the file `go.mod` as a minor version of golang specified, which is currently `1.16`.

At the same time, the Docker image (source at https://github.com/jenkins-infra/docker-hashicorp-tools) defines a specific version of golang, which is `1.17.6`: https://github.com/jenkins-infra/docker-hashicorp-tools/blob/main/Dockerfile#L4 (as for today).

We need to ensure that the file `go.mod` is kept up to date by updatecli to match the golang minor version of the Docker image.

Expected outcome of this issue is a PR, automatically opened by updatecli, that would update the gomod file to the same 1.x version as the current docker image.

Some technical elements:

- The Docker image version used by this repo is defined in the file `ci-pod-template.yml`: https://github.com/jenkins-infra/aws/blob/main/ci-pod-template.yml#L7.
  - Useful to determine "which" version is currently" used for updatecli.
- ~There is already an updatecli process in place with manifest covering terraform dependencies: https://github.com/jenkins-infra/aws/tree/main/updatecli (only need to add a manifest)~

**Comment by smerle33** [comment]
- [ ] Need to prepare the updatecli process, with folder and call within jenkinsfile.
  - [ ] add a jenkinsfile which calls the updatecli() library
  - [ ] open a PR in jenkins-infra/kubernetes-management to add jenkins pipeline for this repo in infra.ci
- [ ] add updatecli manifest inspired from : https://github.com/updatecli/updatecli/blob/main/updatecli/updatecli.d/golang.yaml
  - [ ] use the last golang version as source (search for example in updatecli see link above)

**Comment by smerle33** [comment]
need to find the internalId of the repo to add in kubernetes-management helmfile

**Comment by lemeurherve** [comment]
These ids are fictionals and man-made, use the current date as a pattern :)
