### ISSUE TITLE
Keep track of terraform version in the README.adoc

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/shared-tools#11]
update the updatecli manifest from shared-tool hashicorp-tools to chained the terraform version from in blame format : https://github.com/jenkins-infra/docker-hashicorp-tools/blob/0.4.4/Dockerfile

_Originally posted by @lemeurherve in https://github.com/jenkins-infra/shared-tools/issues/8#issuecomment-1066524141_

**Comment by dduportal** [comment]
Closed by https://github.com/jenkins-infra/shared-tools/pull/12, great job!
