### ISSUE TITLE
Changes on this repo should trigger dependant terraform jobs

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/shared-tools#139]
After merging a change here, we should trigger jobs on every terraform job depending on this repo so these changes are applied to these jobs, potentially creating or changing resources.

Ex:
- #138
- Manually triggered main build on azure repo resulting in 2 new resources: https://infra.ci.jenkins.io/job/terraform-jobs/job/azure/job/main/1055/

**Comment by sridamul** [comment]
@lemeurherve Can you throw some light on the implementation part?

**Comment by lemeurherve** [comment]
I'm sorry this issue requires advanced knowledge of Jenkins infrastructure, this isn't a good issue to start with.

I'm not even sure to want to keep this issue open to be honest.
