### ISSUE TITLE
updatecli: keep track of terraform version

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/shared-tools#8]
Same spirit as jenkins-infra/shared-tools#1 but with the terraform version :)

**Comment by smerle33** [comment]
Add a updatecli yaml to keep hashicorp image version uptodate in https://github.com/jenkins-infra/pipeline-library/blob/master/vars/terraform.groovy

**Comment by smerle33** [comment]
change https://github.com/jenkins-infra/docker-hashicorp-tools/blob/main/updatecli/updatecli.d/terraform.yml regex to update to v1.1.x instead of v1.0.x

**Comment by smerle33** [comment]
builds will break on :

jenkins-infra/aws
jenkins-infra/datadog
jenkins-infra/digitalocean

**Comment by smerle33** [comment]
keep going with : 

- [ ]  datadog
- [ ]  digital ocean

**Comment by smerle33** [comment]
checking hashicorp image for terraform version with updatecli within jenkinsfile_k8s in https://github.com/jenkins-infra/aws/blob/main/Jenkinsfile_k8s

**Comment by dduportal** [comment]
Closing as the work is done, great job!
